batch_size: 32
epochs: 100
es_patience: 5
lr: 0.001
model_params:
  num_classes: 5
  # Perslay params
  interval:
  - 0.075
  - 0.145
  steps: 32
  topo_out: 32
  sublevel: True
  k: 2
threshold: 0.001