batch_size: 32
epochs: 100
es_patience: 5
lr: 0.001
model_params:
  num_classes: 5
  # PLLay params
  interval_1:
  - 0.075
  - 0.145
  interval_2:
  - 0.05
  - 0.95
  steps: 32
  topo_out: 32
  sublevel_1: True
  sublevel_2: False
  KK:
  - 0
  - 1
  grid_size:
  - 40
  - 40
  dimensions:
  - 0
  - 1
threshold: 0.001