as_rgb: True  # download 3 channel data if set to True
batch_size: 32
epochs: 100
es_patience: 10
factor: 0.1
lr: 0.001
lr_topo: 0.0001
model_params:
  # ECLayr params
  interval:
  - 0.01
  - 0.99
  steps: 32
  constr: "V"
  sublevel: False
  postprocess_cfg:  # dimensions of postprocess layer
  - 32
  - 32
sch_patience: 5
size: 28
threshold: 0.001