batch_size: 32
epochs: 100
es_patience: 10
lr: 0.001
model_params:
  in_channels: 1
  num_classes: 5
  # ECLayr params
  interval_1:
  - 0.03
  - 0.1
  interval_2:
  - 0.05
  - 0.95
  steps: 32
  topo_out: 32
  sublevel_1: True
  sublevel_2: False
  lam: 138
threshold: 0.001