batch_size: 32
epochs: 100
es_patience: 10
lr: 0.001
model_params:
  in_channels: 1
  num_classes: 5
  # ECLayr params
  interval:
  - 0.03
  - 0.1
  steps: 32
  topo_out: 32
  sublevel: True
threshold: 0.001