batch_size: 32
epochs: 100
es_patience: 5
lr: 0.001
model_params:
  num_classes: 10
  # PLLay params
  interval:
  - 0.053
  - 0.14
  steps: 16
  topo_out: 32
  sublevel: True
  KK:
  - 0
  - 1
  grid_size:
  - 28
  - 28
  dimensions:
  - 0
  - 1
threshold: 0.001